services:
  server: 
    image: delfer/alpine-ftp-server
    container_name: server
    environment:
      - USERS=user42|password42
    networks:
      inquisitor:
        ipv4_address: 172.20.0.2

  client:
    image: jlesage/filezilla
    container_name: client
    networks:
      inquisitor:
        ipv4_address: 172.20.0.3

  inquisitor:
    build: .
    container_name: inquisitor
    privileged: true
    cap_add:
      - NET_ADMIN  # INDISPENSABLE pour l'ARP Spoofing +- capter a revoir
    networks:
      inquisitor:
        ipv4_address: 172.20.0.4
    stdin_open: true 
    tty: true

networks:
  inquisitor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24